# Generated by Django 5.1.4 on 2024-12-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ECOM", "0003_remove_customer_is_sale_remove_customer_sale_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_sale",
            new_name="on_sale",
        ),
    ]
